/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/5.4.1/userguide/multi_project_builds.html
 */
include(":example-app")
include(":example-java-lib1")
include(":example-kotlin-lib2")
include(":example-custom-extensions")
include(":example-custom-apt")

include(":brouter-core")
include(":brouter-api")
include(":brouter-model")
include(":brouter-apt")
include(":brouter-gradle-plugin")
include(":brouter-compile-common")
include(":brouter-runtime-common")

include(":brouter-stub-appcompat")
include(":brouter-stub-androidx")

val appcompat = System.getProperty("brouter.appcompat") == "true"
val compats = setOf("brouter-api", "brouter-apt", "brouter-core")


rootProject.children.forEach {
    if(appcompat && it.name in compats) {
        it.name = it.name + "-appcompat"
    }
}

